name = "Observers"
uuid = "338f10d5-c7f1-4033-a7d1-f9dec39bcaa0"
authors = ["Giacomo Torlai <gttorlai@amazon.com>", "Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.0.7"

[compat]
julia = "1.4"
